server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.178.25.71:3306/yiqing?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 8a78l4j00QPE

mybatis-plus:
  global-config:
    db-config:
      table-underline: false # 设置表明不使用下划线方式
  configuration:
    map-underscore-to-camel-case: false # 设置字段不使用下划线方式

pagehelper:
  propertyName: propertyValue
  reasonable: false
  defaultCount: true # 分页插件默认参数支持 default-count 形式，自定义扩展的参数，必须大小写一致
